name: mccg

channels:
  - conda-forge

dependencies:
  - python=3.9
  - ipykernel
  - scikit-learn=1.3
  - scipy=1.10
  - hdbscan
  - pyyaml
  - gensim=3.8
  - tqdm
  - pip:
    - pinyin

# pip pip install torch==2.1.0 torch_geometric torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.7.0+cu121.html

# pip install torch==2.1.0 torch_geometric torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.7.0+cpu.html