cuda: true
gpu: 0
dataset: whoiswho-micro
mode: test
save_path: dataset/whoiswho-micro
log_dir: .expert_record/whoiswho-micro
predict_result: whoiswho-mini_results.txt
ground_truth_file: dataset/whoiswho-micro/src/test/sna_test_ground_truth.json
layer_shape:
- 100
- 256
- 256
dim_proj_multiview: 128
dim_proj_cluster: 128
th_a:
- 1
th_o:
- 0.5
th_v:
- 2
db_eps:
- 0.1
db_min:
- 4
drop_scheme:
- degree
drop_feature_rate_view1:
- 0.4
drop_feature_rate_view2:
- 0.2
drop_edge_rate_view1:
- 0.4
drop_edge_rate_view2:
- 0.5
seed: 1
lr: 0.0001
epochs: 100
l2_coef:
- 0.2
w_cluster:
- 0.6
t_multiview:
- 0.3
t_cluster:
- 0.3
refine: true
